### PR TITLE
Seeds

### PR DESCRIPTION
**Pull request by oliverLo78**
adding array of wines to home-routes

### CODE REVIEW

**Comment by oliverLo78** [comment]
added Wine Enthusiast Header

**Review by oliverLo78 — COMMENTED** [review]
oops meant to say to approve this one!

**Review by oliverLo78 — COMMENTED** [review]
please approve...basically restarting the whole project 2 again

**Review by ProNevros — APPROVED** [review]
Sorry for the wait, I'm getting back into the groove of working on stuff, too!

**Pull request merged**
